name: tests

on:
  pull_request:
  push:
    branches: 
      - main
        

jobs:
  unit-tests:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn
      - run: yarn test
